<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="calculator" targetNamespace="http://kolia.pp.ru/calculator/" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:tns="http://kolia.pp.ru/calculator/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:message name="calculatePriceRequest">
    <wsdl:part name="distance" type="xsd:double"/>
  </wsdl:message>
  <wsdl:message name="calculatePriceResponse">
    <wsdl:part name="price" type="xsd:double"/>
  </wsdl:message>
  <wsdl:portType name="Calculator">
    <wsdl:operation name="calculatePrice">
      <wsdl:input message="tns:calculatePriceRequest"/>
      <wsdl:output message="tns:calculatePriceResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="calculatorSOAP" type="tns:Calculator">
    <soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="calculatePrice">
    <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="http://kolia.pp.ru/calculator/NewOperation"/>
      <wsdl:input>
    <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://kolia.pp.ru/calculator/" use="encoded"/>
      </wsdl:input>
      <wsdl:output>
    <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://kolia.pp.ru/calculator/" use="encoded"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CalculatorService">
    <wsdl:port name="calculatorSOAP" binding="tns:calculatorSOAP">
    <soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://localhost:8080/shipment/services/calculatorSOAP"/>
    </wsdl:port>
  </wsdl:service>
<plnk:partnerLinkType name="CalculatorLinkType">
   <plnk:role name="calculator">
      <plnk:portType name="tns:Calculator"/>
   </plnk:role>
</plnk:partnerLinkType>
</wsdl:definitions>
